app.controller('main',['$scope','$stateParams','adds',function($scope,$stateParams,adds){
				adds.gets().then(function(res){
					$scope.val=res.data;
				});
				$scope.bools1='dlbg';
				$scope.bools2='';
				$scope.bools3='';
				$scope.fn1=function(){
					$scope.bools1='dlbg';
					$scope.bools2='';
					$scope.bools3='';
				}
				$scope.fn2=function(){
					$scope.bools1='';
					$scope.bools2='dlbg';
					$scope.bools3='';
				}
				$scope.fn3=function(){
					$scope.bools1='';
					$scope.bools2='';
					$scope.bools3='dlbg';
				}


}]);
app.config(function($stateProvider,$urlRouterProvider){
	$stateProvider
		.state('one',{
			url:'/one',
			templateUrl:'view/view1.html',
			controller:'main'
		})
		.state('two',{
			url:'/two',
			templateUrl:'view/two.html',
			controller:'main'
		})
		.state('three',{
			url:'/three',
			templateUrl:'view/view1.html',
			controller:'main'
		})
		.state('four',{
			url:'/four',
			templateUrl:'view/two.html',
			controller:'main'
		})
		.state('five',{
			url:'/five',
			templateUrl:'view/two.html',
			controller:'main'
		});
	$urlRouterProvider.otherwise('one');
})