app.controller('main',['$scope','$stateParams','adds',function($scope,$stateParams,adds){
				console.log($stateParams.id);
				adds.gets().then(function(res){
					$scope.val=res.data;
				})
				$scope.bools=false;
				$scope.par1='︾';
				$scope.par2='︾';
				$scope.par3='︾';
				$scope.fn1=function(item){
					$scope.bools=!$scope.bools;
					if($scope.bools){
						$scope.par1='︽';
					}else{
						$scope.par1='︾';
					}
				}
				$scope.fn2=function(item){
					$scope.bools=!$scope.bools;
					if($scope.bools){
						$scope.par2='︽';
					}else{
						$scope.par2='︾';
					}
				}
				$scope.fn3=function(item){
					$scope.bools=!$scope.bools;
					if($scope.bools){
						$scope.par3='︽';
					}else{
						$scope.par3='︾';
					}
				}
			}]);
			app.config(function($stateProvider,$urlRouterProvider){
				$stateProvider
					.state('search',{
						url:'/search/:id',
						templateUrl:'view/view1.html',
						controller:'main'
					})

				$urlRouterProvider.otherwise('/search/0');
			})